logging.level.root: INFO
server.port: 8080

# Local dev credentials for mySQL
spring.datasource:
  url: jdbc:mysql://localhost/springtest
  username: dev
  password: password
  driver-class-name: com.mysql.jdbc.Driver
  tomcat:
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1

spring.jpa:
  hibernate:
    ddl-auto: create
  show-sql: true